{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime-ktx",
    "version": "2.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.8.3-sources.jar",
          "url": "navigation-runtime-ktx-2.8.3-sources.jar",
          "size": 4458,
          "sha512": "f30643b2bb81343a879bc4e88c7457e722725afba3136c589d85e6fca1825da6964cc54525e97a03084f5bd6a1c922dded6556dc02081891b6052c2e4ddb47a5",
          "sha256": "a012de5a17cdfafc06ab48be56b442fbcfa64e8459beb5017459d6f9030ede72",
          "sha1": "79cb4cd4f96c6a64a1fc953a9e7111e56c394297",
          "md5": "38d54d2f5f3f2a6d3be9359af681b8e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.8.3.aar",
          "url": "navigation-runtime-ktx-2.8.3.aar",
          "size": 5627,
          "sha512": "d6c3356525983d6c0ddd9b9a520e0e20171f009b3294a433fe90040e44528f3dd5e88a961ad107bb901791e64260cc1f9ece2fdaee1a4c298a5c82e205b6f094",
          "sha256": "25b964a8249796edd0dec9dd2a5c56998116537b85e973cf2c177ef1c1f731bc",
          "sha1": "f063bf8bde2d8bb14439cccd3107d83d9b370a22",
          "md5": "9eab594baa46fb0b6b58b8b3712f2738"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.8.3.aar",
          "url": "navigation-runtime-ktx-2.8.3.aar",
          "size": 5627,
          "sha512": "d6c3356525983d6c0ddd9b9a520e0e20171f009b3294a433fe90040e44528f3dd5e88a961ad107bb901791e64260cc1f9ece2fdaee1a4c298a5c82e205b6f094",
          "sha256": "25b964a8249796edd0dec9dd2a5c56998116537b85e973cf2c177ef1c1f731bc",
          "sha1": "f063bf8bde2d8bb14439cccd3107d83d9b370a22",
          "md5": "9eab594baa46fb0b6b58b8b3712f2738"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.8.3-versionMetadata.json",
          "url": "navigation-runtime-ktx-2.8.3-versionMetadata.json",
          "size": 2839,
          "sha512": "7217a5c665e4d0a448aed41692f2864d65cdaa3e8ff6ad3b60830069ffa5ceef900e245a2b5e8405489b7d84a400df6cabca2ea06f913833ee7414182e179dbd",
          "sha256": "974a7ade0887f9b1a8142ac91041d064dd0792183a6a19ceb77a51215fc5f302",
          "sha1": "3002de81bae1156c51ab2e1a935b5becc7fb81c1",
          "md5": "20d32ff0cd1696e8714c00d84df9aedd"
        }
      ]
    }
  ]
}