{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-compose",
    "version": "2.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.8.3-sources.jar",
          "url": "navigation-compose-2.8.3-sources.jar",
          "size": 23550,
          "sha512": "cf2ee636c35a78019525f14faefdde5d2af12074c10eab9d5c3afa7e837c4560159ab1e3f5410c526c01299760948a6370bc873e49da9aab94177570a855cc8a",
          "sha256": "c8e18320004a40a2153b2437cbd0fa35df984b4dc6dbff2e9bae86bfe9635ca6",
          "sha1": "e88bc5dce67d185113a30b291b92c18c6ac98ad6",
          "md5": "7d031234024b9e08b1dd0c080e88db95"
        },
        {
          "name": "navigation-compose-2.8.3-samples-sources.jar",
          "url": "navigation-compose-2.8.3-samples-sources.jar",
          "size": 11296,
          "sha512": "de1a633658a10a834f78203651defdba1b51fc96de5ecbe0308007b0e0e6f502aa7da40acbe0c229330c5f3b413ddf2d3614263eba735c709ce2138e3df53394",
          "sha256": "3e15db75e78018d734ba4839ac0b0ca3b067415af1d5850a2810dcacd73f411e",
          "sha1": "1900b29173e399a9b4584cb84ca2067222fc0517",
          "md5": "3e636d70a85d8e869c462b639a97317a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.8.3.aar",
          "url": "navigation-compose-2.8.3.aar",
          "size": 1227662,
          "sha512": "b7af9c8387c7b4845fdc8cc1db21e64ed3f7dfbc6a3b2582c07d43976d96f6cda30bbeb2a950a9f1a174583c3e2322c2aa32707b15d5c593391b970fc4a75656",
          "sha256": "d687e428b5efbb6266066ae45e522a305e0d11160b26f67f4d513586996c5c41",
          "sha1": "051a3dc042bb316ac7b49d73ad6eacecc6f6dd97",
          "md5": "efe83820ecca1050d962aa07756a085a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.8.3.aar",
          "url": "navigation-compose-2.8.3.aar",
          "size": 1227662,
          "sha512": "b7af9c8387c7b4845fdc8cc1db21e64ed3f7dfbc6a3b2582c07d43976d96f6cda30bbeb2a950a9f1a174583c3e2322c2aa32707b15d5c593391b970fc4a75656",
          "sha256": "d687e428b5efbb6266066ae45e522a305e0d11160b26f67f4d513586996c5c41",
          "sha1": "051a3dc042bb316ac7b49d73ad6eacecc6f6dd97",
          "md5": "efe83820ecca1050d962aa07756a085a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.3"
          },
          "reason": "navigation-compose is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-compose-2.8.3-versionMetadata.json",
          "url": "navigation-compose-2.8.3-versionMetadata.json",
          "size": 21861,
          "sha512": "b86d72bd5e4e774e7067d744e18f842484c3dc902c707029a2ff44a48b92992559bb035215cb04ea13f9ea9b2b1cb85f993714f92cc829e6a0953ab653a5b2ea",
          "sha256": "58bb74fc9bebe148e4926d56000404b3f7cea0cf87a69a2cd94246b301820195",
          "sha1": "365c3bcdb4c89850ee25995ec2b0e5fb1fe1e4b7",
          "md5": "d56b78f1f1d757355f678c9f9ffcfa26"
        }
      ]
    }
  ]
}